Vagrant.configure("2") do |config|
  
config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.name = "Linux-02"
end 
### linux test vm ###
  config.vm.define "linux02" do |t|
    t.vm.box = "bento/ubuntu-22.04"
    t.vm.network "private_network", ip: "192.168.56.97"
    t.vm.provision "shell", path: "provision/initialize.sh"
    t.vm.provision "shell", reboot: true 
    t.vm.provision "shell", path: "provision/add_to_domain.sh"
    t.vm.provision "shell", reboot: true
    t.vm.provision "shell", path: "provision/install_node_exporter.sh"
    t.vm.provision "shell", path: "provision/puppetnode_setup.sh"
    end
  
end
